# Generated by Django 4.0.2 on 2022-06-23 19:26

import apps.base.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Тип файла')),
                ('created_date', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': '(Справочник) Тип файла',
                'verbose_name_plural': '(Справочник) Типы файлов',
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=510, verbose_name='Название файла')),
                ('path', models.FileField(upload_to=apps.base.models.get_file_path, verbose_name='Файл')),
                ('created_date', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
                ('is_private', models.BooleanField(default=False, verbose_name='Закрытый файл')),
                ('file_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.filetype', verbose_name='Тип файла')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы',
            },
        ),
    ]
