# Generated by Django 4.0.2 on 2022-06-29 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='prefix',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Префикс'),
        ),
    ]
