# Generated by Django 4.0.2 on 2022-07-02 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_file_prefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='size',
            field=models.FloatField(default=0, verbose_name='Размер файла в МБ'),
        ),
    ]
