# Generated by Django 4.0.2 on 2022-07-06 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_file_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='in_basket',
            field=models.BooleanField(default=False, verbose_name='В корзине'),
        ),
    ]
