# Generated by Django 4.0.2 on 2022-07-07 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_file_in_basket'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='head_folder',
            field=models.BooleanField(default=False, verbose_name='Главная папка с файлами'),
        ),
    ]
