# Generated by Django 4.0.2 on 2022-07-14 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_file_head_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file_version',
            field=models.ManyToManyField(to='base.File', verbose_name='Версии файлов'),
        ),
    ]
