# Generated by Django 4.0.2 on 2022-07-16 15:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('folder', '0007_folder_updated_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0009_file_updated_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSharedPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_only', models.BooleanField(default=True, verbose_name='Только чтение')),
            ],
            options={
                'verbose_name': 'Права пользователя в папках и файлах',
                'verbose_name_plural': 'Права пользователя в папках и файлах',
            },
        ),
        migrations.AddField(
            model_name='file',
            name='allow_users',
            field=models.ManyToManyField(through='base.UserSharedPermission', to='base.File'),
        ),
        migrations.AddField(
            model_name='usersharedpermission',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.file', verbose_name='Файл'),
        ),
        migrations.AddField(
            model_name='usersharedpermission',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='folder.folder', verbose_name='Папка'),
        ),
        migrations.AddField(
            model_name='usersharedpermission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
