# Generated by Django 4.0.2 on 2022-07-16 16:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('folder', '0011_alter_folder_allow_users'),
        ('base', '0012_rename_file_usersharedpermission_file_to_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usersharedpermission',
            unique_together={('user', 'folder_to', 'file_to')},
        ),
    ]
