#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


python manage.py migrate
python manage.py collectstatic --noinput

pip install debugpy && python -m debugpy --wait-for-client --listen 0.0.0.0:5678 -m uvicorn config.asgi:application --host 0.0.0.0 --reload --reload-delay 1
