# Generated by Django 4.0.2 on 2022-06-30 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folder', '0002_folder_parent_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='in_basket',
            field=models.BooleanField(default=False, verbose_name='В корзине'),
        ),
    ]
