# Generated by Django 4.0.2 on 2022-07-16 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folder', '0008_folder_allow_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='allow_users',
            field=models.ManyToManyField(related_name='folder_id', through='base.UserSharedPermission', to='folder.Folder'),
        ),
    ]
