# Generated by Django 4.0.2 on 2022-07-16 15:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
        ('folder', '0010_alter_folder_allow_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='allow_users',
            field=models.ManyToManyField(related_name='folder_to', through='base.UserSharedPermission', to=settings.AUTH_USER_MODEL),
        ),
    ]
